# Generated by Django 5.2.16 on 2026-07-08 15:26

import competitions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signage',
            fields=[
                ('id', models.CharField(default=competitions.models.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('content', models.JSONField(blank=True, default=list)),
                ('news', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'signage_settings',
            },
        ),
    ]
