# Generated by Django 5.2.16 on 2026-07-08 15:12

import competitions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.CharField(default=competitions.models.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('shorted', models.CharField(max_length=255, unique=True)),
                ('transfer', models.CharField(max_length=2048)),
            ],
            options={
                'db_table': 'short_urls',
            },
        ),
    ]
