name: General Issue
description: Report a general issue or ask a question
title: "[General]: "
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template for general issues or questions.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the issue or question.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about the issue or question.
    validations:
      required: false

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Add any other information or screenshots that might be helpful.
    validations:
      required: false
