# Generated by Django 5.2.16 on 2026-07-08 15:04

import competitions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.CharField(default=competitions.models.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('competition_id', models.CharField(db_index=True, max_length=24)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'competition_fields',
                'constraints': [models.UniqueConstraint(fields=('competition_id', 'name'), name='uniq_field_competition_name')],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.CharField(default=competitions.models.new_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('competition_id', models.CharField(db_index=True, max_length=24)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'competition_rounds',
                'constraints': [models.UniqueConstraint(fields=('competition_id', 'name'), name='uniq_round_competition_name')],
            },
        ),
    ]
